[test_config]
name = "bimm"
engine = "Ptrace"

workspacea = true
exclude = [
  "examples/swin_tiny",
  "examples/firehose_loadtest"
]

coveralls="nHrsJRySHlIGNh3SsPt7yXCIvKC2Esi8e"

timeout = "10m"
fail-under = 80

run-types = ["Tests"]

