[package]
name = "bimm-contracts"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/bimm-contracts/latest/"
description = "Runtime contracts for the bimm framework"

[lints]
workspace = true

[dependencies]
burn = { workspace = true }

[dev-dependencies]
burn = { workspace = true, features = ["ndarray"] }

[features]
nightly = []
