[package]
name = "bimm-contracts"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
description = "Runtime contracts for the bimm framework"

[lints]
workspace = true

[dependencies]
burn = { workspace = true }

[features]
nightly = []
