[package]
name = "bimm-contracts"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
documentation = "https://docs.rs/bimm-contracts/latest/"
description = "Runtime contracts for the bimm framework"

[lints]
workspace = true

[dependencies]
bimm-contracts-macros = { version = "0.2.1", path = "../bimm-contracts-macros" }

burn = { workspace = true }

[dev-dependencies]
burn = { workspace = true, features = ["ndarray"] }
criterion = { workspace = true }

[[bench]]
name = "contracts"
harness = false

[features]
default = []

nightly = []
