[package]
name = "swin_tiny"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
burn = { workspace = true, features = ["train", "autodiff", "cuda", "fusion", "vision", "dataset"] }

clap = { workspace = true, features = ["derive"] }

serde = { workspace = true, features = ["derive"] }

bimm = { workspace = true }
bimm-firehose = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }

rs-cinic-10-index = { workspace = true }
strum = { workspace = true }
enum-ordinalize = { workspace = true }

[features]
nightly = []