[package]
name = "swin_tiny"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true


[lints]
workspace = true

[dependencies]
burn = { workspace = true, features = ["train", "autodiff", "cuda", "fusion"] }

bimm-swin = { path = "../../crates/bimm-swin" }
rs-cinic-10-index = { workspace = true }
rs-cinic-10-burn = { workspace = true }
strum = { workspace = true }
enum-ordinalize = { workspace = true }
rand = "0.9.1"

