[package]
name = "swin_tiny"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
burn = { workspace = true, features = ["train", "autodiff", "cuda", "fusion", "vision", "dataset"] }
serde = { workspace = true, features = ["derive"] }

clap = { workspace = true, features = ["derive"] }

bimm = { workspace = true }
bimm-firehose = { workspace = true }
bimm-firehose-image = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }

[features]
nightly = []