[package]
name = "swin_tiny"
edition.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
burn = { workspace = true, features = ["train", "autodiff", "cuda", "fusion", "vision", "dataset"] }

serde = { workspace = true, features = ["derive"] }

bimm = { workspace = true }
bimm-firehose = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }

rs-cinic-10-index = { version = "^0.2.0" }
strum = {  version = "^0.27.1" }
enum-ordinalize = { version = "^4.3.0" }

[features]
nightly = []