[package]
name = "bimm"
edition.workspace = true
version.workspace = true
license.workspace = true
description = "burn image models"

[lints]
workspace = true

[dependencies]
burn = { workspace = true }
bimm-contracts = { workspace = true }

[dev-dependencies]
burn = { workspace = true, features = ["ndarray"] }

num-traits = { workspace = true }
hamcrest = { workspace = true }

[features]
burn_0_18_0 = []

