name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined

    steps:
      - run: rustup toolchain install stable --profile minimal

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Format
        run: cargo fmt --check

      - name: Clippy Lint
        run: cargo clippy --check

      - name: Build and Test
        run: |
          cargo tarpaulin --verbose --coveralls=${{ secrets.COVERALLS_REPO_TOKEN }}

