name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - run: rustup toolchain install stable --profile minimal

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Tools
        run: |
          cargo install cargo-tarpaulin

      - name: Check Format
        run: cargo fmt --check

      - name: Clippy Lint
        run: cargo clippy --no-deps

      - name: Build and Test
        run: |
          cargo tarpaulin --coveralls=${{ secrets.COVERALLS_REPO_TOKEN }}
